#!/bin/bash -x

ORG_PATH="github.com/vtolstov"
REPO_PATH="${ORG_PATH}/svirtnet"

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/third_party

mkdir -p $GOBIN

wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz -O go.tar.gz
tar -zxf go.tar.gz
export PATH=$PATH:$(pwd)/go/bin

if [ ! -h $GOPATH/src/${REPO_PATH} ]; then
        mkdir -p $GOPATH/src/${ORG_PATH}
        ln -s ../../../.. $GOPATH/src/${REPO_PATH} || echo "exit 255"
fi

go build -x -o bin/svirtnet ${REPO_PATH}
