#!/bin/bash -x

ORG_PATH="github.com/vtolstov"
REPO_PATH="${ORG_PATH}/cloudmeta"
#VERSION=`git describe --long`
#BUILD_TIME=`date +%FT%T%z`
#LDFLAGS="-X main.Version=${VERSION} -X main.BuildTime=${BUILD_TIME}"


rm -rf bin tmp

export GO15VENDOREXPERIMENT=1
export GOPATH=$(pwd)/gopath
export PATH=$GOROOT/bin:$PATH:$(pwd)/goroot/bin
mkdir -p $GOPATH
mkdir -p bin
mkdir -p tmp

go version | grep -q go1.5

if [ "x$?" != "x0" ]; then
    export GOROOT=$(pwd)/goroot
    mkdir -p $GOROOT
    wget -q https://storage.googleapis.com/golang/go1.5.linux-amd64.tar.gz -O tmp/go.tar.gz
    tar --strip-components=1 -C $GOROOT -xf tmp/go.tar.gz
fi

if [ ! -h $GOPATH/src/${REPO_PATH} ]; then
        mkdir -p $GOPATH/src/${ORG_PATH}
        ln -s ../../../.. $GOPATH/src/${REPO_PATH} || echo "exit 255"
fi

set -e

GOOS=linux GOARCH=amd64 go build -x -ldflags "${LDFLAGS}" -tags netgo -o bin/svirtnet ${REPO_PATH}
