#!/bin/bash -x

ORG_PATH="github.com/vtolstov"
REPO_PATH="${ORG_PATH}/svirtnet"

export GOBIN=$(pwd)/bin
export GOPATH=$(pwd)/third_party

mkdir -p $GOBIN

GO=$(which go)
if [ "x${GO}" = "x" ]; then
    wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz -O go.tar.gz
    tar -zxf go.tar.gz
    rm -f go.tar.gz
    export PATH=$(pwd)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin
    export GOROOT=$(pwd)/go
fi

if [ ! -h $GOPATH/src/${REPO_PATH} ]; then
        mkdir -p $GOPATH/src/${ORG_PATH}
        ln -s ../../../.. $GOPATH/src/${REPO_PATH} || echo "exit 255"
fi

go build -a -x -o bin/svirtnet ${REPO_PATH}
